'use strict';
// Classroom sequence: all prompts and responses are local; no AI service is called.
const workshopGroups=[['情境开场与参与约定',0,5],['发现情绪',5,12],['理解情绪',12,20],['给自己一点缓冲',20,27],['表达：试一次，再试一次',27,39],['迁移与求助',39,46],['带走一个方法',46,50]];
const participation='先自己想 → 同桌交流 → 自愿分享；也可以默想、书写或旁观。';
const classroomStory='合作展示时，你还没有说完，同组同学就接着讲了。';
const methodAnswers=['','',''];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=(rows)=>`<div class="work-cards">${rows.map((r,i)=>`<article class="work-tone-${i%3}"><span class="work-symbol">${['①','②','③'][i%3]}</span><h2>${r[0]}</h2><p>${r[1]}</p></article>`).join('')}</div>`;
const workTitle=(title,sub='')=>lessonHead(title,sub);
const task=(title,sub,rows,foot='')=>workTitle(title,sub)+cards(rows)+(foot?takeaway(foot):'');
function roundControls(){return `<div class="round-clock"><strong id="roundClock">${timeText(roundRemaining)}</strong><button data-round="60">甲 · 60秒</button><button data-round="60">乙 · 60秒</button><button id="roundPause">${roundRunning?'暂停':'继续'}</button><span>教师按实际节奏切换角色；不自动翻页。</span></div>`}
function tryExpression(second=false){return workTitle(second?'带着反馈，再说一次。':'先试一次：你会怎样说？',classroomStory)+`<div class="work-role-grid"><section class="work-tone-0"><h2>说的人</h2><p>${second?'保留原意，把事情、感受与请求说清楚。':'按自己的方式说，不先看标准句式。'}</p><p>甲说60秒 → 交换 → 乙说60秒</p></section><section class="work-tone-1"><h2>听的人</h2><p>${second?'复述：“我听懂了，你希望……”':'先听完，只记下听懂和不清楚的地方。'}</p><p>不评价对方“脾气好不好”。</p></section></div>${roundControls()}${takeaway('先用30秒准备，最后30秒记一句。没有同桌或不愿说，可以写两句话。')}`}
function feedback(){return task('同伴反馈：只检查三件事。','甲反馈60秒，再交换。先说听懂了什么，再问一处不清楚。', [['事情','“我听到，刚才发生了……”'],['感受','“我听到，你有点……”'],['请求','“你希望我具体怎么做？”']], '反馈句：“我听懂了……；还想问清楚……” 不替同伴打分。')}
function expressionModel(){return task('三句话，让别人更容易听懂。',classroomStory,[['描述事情','“刚才我还没说完，你就接着讲了。”'],['表达感受与需要','“我有点着急，我想把自己的部分说完。”'],['提出具体请求','“下次可以等我说完，再接着讲吗？”']], '这是一种表达方式，不是必须背的台词。具体请求也不保证对方配合。')}
function methodCard(){return workTitle('留下一个，你愿意使用的方法。','可以继续写故事人物，不用写姓名，也不用提交。')+`<div class="method-card">${['遇到类似情况，我可能感到：','我愿意先试的一步：','需要支持时，我可以找：'].map((label,i)=>`<label><span>${label}</span><textarea data-method-answer="${i}" rows="1" maxlength="120" placeholder="可以写在自己的纸上，也可由教师输入虚构示例">${esc(methodAnswers[i])}</textarea></label>`).join('')}</div><div class="method-actions"><button id="printMethod">打印这张卡</button><button id="clearMethod">清空填写</button><span>只在本页临时保留，刷新即清空；不上传。</span></div>${takeaway('检查：具体吗？现在能开始吗？安全吗？不要求马上开心。')}`}
const workshopSlides=[
 {g:0,m:2,name:'开场故事',kind:'想一想',view:()=>workTitle('同一件事，感觉会一样吗？','“明天，每人上台讲一分钟。”')+`<div class="work-hero"><section>${cards([['我可能期待','想试试看'],['我可能紧张','有些担心'],['我还说不清','几种感受都有']])}<p class="work-instruction">自己想20秒 → 同桌各说20秒 → 邀请2位分享。</p></section>${sceneArt('presentation.webp','感受可以不同')}</div>`,notes:'用20秒读故事。给每个人20秒安静思考，同桌各20秒说一个词，再邀2人各15秒分享，最后30秒收束。可以用手势指选项。不同回答都先回应“我听到了”，不追问私人经历。'},
 {g:0,m:3,name:'目标与约定',kind:'一起约定',view:()=>task('今天带走三句话。','可以练故事人物，不必讲自己的困扰。',[['说清感受','“我有点……”'],['选择行动','“此刻我可以先……”'],['找到支持','“需要帮助，我可以找……”']],participation),notes:'1分钟介绍三个目标，1分钟约定不嘲笑、不追问隐私、允许旁观，1分钟让学生选择今天想多练的一句话。没人说时教师示范“我想练把请求说具体”。不承诺同伴保守安全风险的秘密。'},
 {g:1,m:3,name:'情绪词与强度',kind:'选词与解释',view:()=>wordPalette()+`<p class="work-instruction">替小宁选一个词：自己想20秒 → 同桌各说30秒 → 自愿分享。</p>`,notes:'30秒解释词与强度，20秒独立选词，同桌各30秒，40秒邀请两位分享，30秒归纳。词卡不是诊断或健康评分；混合感受与说不清也可以。若都说紧张，追问“会不会同时有一点期待？”不要求统一答案。'},
 {g:1,m:2,name:'身体线索',kind:'观察与解释',view:bodySignals,notes:'30秒看图，20秒自己选一个可能的身体线索，同桌各20秒描述，30秒解释一个信号不能判断一种情绪。若说“心跳快就是害怕”，追问“刚跑完步也会吗？”身体持续不适可找校医，不简单归因于情绪。'},
 {g:1,m:2,name:'情绪的作用',kind:'简短理解',view:emotionJobs,notes:'1分钟以担心和生气说明可能的功能；30秒同桌各举一个安全行动；30秒收束。若说“生气所以可以推人”，回应“感受能理解，行动仍需保护彼此”。不逐字读四行，不要求背理论名称。'},
 {g:2,m:3,name:'三格情境',kind:'观察与讨论',view:storyComic,notes:'30秒读事件，30秒独立分辨观察和解释，1分钟同桌讨论两种可能，1分钟请两位分享和教师归纳。先收集答案再解释：感受是真的，猜测可以核实，现实处境也需要处理。'},
 {g:2,m:3,name:'换一种可能',kind:'每个人都试',view:()=>task('你观察到了什么？还有什么可能？','朋友经过，没有回应你的招呼。',[['先想30秒','只说看到或听到的事。'],['同桌各45秒','提出另一种可能，再说一个核实方式。'],['分享与追问60秒','“怎样了解情况，既具体又安全？”']], '如果已经受到伤害，可以直接求助，不必先证明自己猜得对。'),notes:'按30秒独立想、同桌各45秒、分享60秒执行，共180秒。邀请最多2位各15秒，其余30秒教师追问与收束。若说“他肯定讨厌我”，问“哪些是观察，哪些还不知道？”若说“都是我想多了”，提醒真实处境也重要。'},
 {g:2,m:2,name:'理解的边界',kind:'回应刚才的疑问',view:()=>task('换一种理解，不是强迫自己乐观。','给尚未确认的原因留一点空间。',[['已经发生','“我打了招呼，他没有回应。”'],['暂未确认','“他为什么没有回应，还不清楚。”'],['可以选择','找合适时候问一问，或请人协助。']], '解释会影响感受；关系、身体状态和真实环境也会影响我们。'),notes:'用前面学生的一种回答讲解1分钟；30秒各自改一句确定性判断；30秒自愿分享或教师示范。不讲模型名称，不把困难全部归因于想法。'},
 {g:3,m:1,name:'为什么练观察',kind:'方法用途',view:()=>task('给自己一点缓冲，再选下一步。','观察具体物品，帮助注意重新回到眼前。',[['可以睁眼','自然呼吸，不用憋气或刻意深呼吸。'],['可以走神','发现后，愿意时再回来。'],['可以停止','不舒服就停下来，找老师陪。']], '目标不是清空想法，也不是比谁更放松。'),notes:'用1分钟说明用途、选择观察物品或身体支撑、退出选择。准备好后再到下一页按播放。本环节不诊断、不评分。'},
 {g:3,m:1,name:'第一轮观察',kind:'60秒练习',original:4,view:()=>workTitle('选一种，试60秒。','观察物品，或留意身体支撑。')+`<div class="work-practice">${timerPanel('ground')}<section>${sceneArt('observe.webp','跟着自己的节奏')}<div class="chips"><button data-method="0">观察物品</button><button data-method="1">留意支撑</button></div><p>随时可暂停或旁观。</p></section></div>`,notes:'点击“开始有声练习”。完整60秒计时包含语音之间的安静观察时间。老师不叠加讲解。有人不适时允许退出，必要时成人陪伴。'},
 {g:3,m:2,name:'交流发现',kind:'同桌交流',view:()=>task('刚才，你发现了什么？','先想20秒，同桌各说30秒，最后自愿分享。',[['看到了什么','颜色、形状、边缘或身体支撑。'],['走神了吗','走神也正常，愿意时可以回来。'],['要调整什么','第二轮可以换一种观察方式。']], '不比较谁更放松，也不需要报告自己的心情。'),notes:'20秒想、30秒甲、30秒乙、40秒分享与总结。若说“没用”，问“你有没有注意到一个具体细节？”再说明不以放松判断成败；不喜欢可以换方式或旁观。'},
 {g:3,m:1,name:'再试一轮',kind:'60秒再练',original:4,view:()=>workTitle('愿意的话，再试一轮。','可以换一种方式，也可以旁观。')+`<div class="work-practice">${timerPanel('ground')}<section>${sceneArt('window.webp','不用追求一样的感觉')}<div class="chips"><button data-method="0">观察物品</button><button data-method="1">留意支撑</button></div><p>练习之后，再决定下一步。</p></section></div>`,notes:'可重复60秒音频，或关闭语音安静观察；随时可退出。前一轮已不适者不要求再次尝试。'},
 {g:3,m:2,name:'把缓冲接到行动',kind:'迁移',view:practiceBridge,notes:'20秒默想“现在可做的一步”，同桌各30秒，40秒分享和归纳。若说“我要努力”，追问“接下来一分钟，你会先做什么？”观察不是替代处理困难。'},
 {g:4,m:3,name:'第一次尝试',kind:'第一轮表达',round:true,view:()=>tryExpression(false),notes:'30秒读情境并各自想一句，甲说60秒、乙听；乙说60秒、甲听；最后30秒各自记住或写下原句。先不出示表达模板，不打断纠正。无人愿说时允许写下或在心里排练。'},
 {g:4,m:2,name:'同伴给反馈',kind:'只反馈清晰度',view:feedback,notes:'甲给乙60秒反馈，乙给甲60秒。只问事实、感受、请求有没有听懂。若反馈“你这样不对”，教师改示范“我听懂了你着急，还不清楚你希望我怎样做”。不评分、不判断谁情绪更好。'},
 {g:4,m:2,name:'学一个表达方法',kind:'需要时讲方法',view:expressionModel,notes:'1分钟讲解事实—感受与需要—具体请求；30秒让学生找原句中可补充的一处；30秒示范。理论此时用于回答刚才反馈中出现的问题，不要求背模板。'},
 {g:4,m:3,name:'修改后再试',kind:'第二轮表达',round:true,view:()=>tryExpression(true),notes:'30秒各自修改；甲说60秒、乙复述；乙说60秒、甲复述；30秒记下第二次说法。可保留第一次已经清楚的部分，不要求为了改变而改变。'},
 {g:4,m:2,name:'看见哪里更清楚',kind:'前后对照',view:()=>task('比较两次：哪一处更清楚了？','先自己对照30秒，同桌各说30秒，再邀请1位分享。',[['第一次','我原来说的是：“……”'],['第二次','我修改后说的是：“……”'],['我发现','事情、感受、请求，哪一处更容易听懂？']], '没有明显变化也没关系。练的是表达，不是保证别人听话。'),notes:'30秒独立对照、同桌各30秒、30秒自愿分享或教师示范。若说“没进步”，问“有哪一处已经清楚，可保留下来？”评价具体、可行、安全，不比谁表现最好。'},
 {g:5,m:2,name:'换故事选行动',kind:'迁移练习',view:()=>task('换一个故事，你先做什么？','小宁准备小测时，发现一道题总是做不出来。',[['我可能感到','自己想20秒：给感受找一个词。'],['我先做一步','同桌各30秒：说一个具体、安全的行动。'],['我可以找谁','分享40秒：需要时请谁协助？']], '“圈出卡点，下课问老师”比“我要加油”更具体。'),notes:'按20+30+30+40秒执行。若学生说休息，追问“休息后是否还需要帮助？”不把休息等同逃避；根据身体和环境选择。'},
 {g:5,m:1,name:'看看怎样陪伴',kind:'30秒对话＋辨认',original:7,view:()=>workTitle('听一段对话：哪句在回应感受？','看完后，和同桌各说一句发现。')+cartoon(),notes:'10秒说明观察任务、30秒有声对话、同桌各10秒辨认回应感受或询问需要。播放出现问题时教师读两句示例，按时进入支持地图，不补播叠加时间。'},
 {g:5,m:2,name:'支持地图',kind:'找到支持',view:supportMap,notes:'30秒自己默想一个可信任的人，不公开姓名；同桌各30秒练虚构求助句；30秒总结。若第一位没回应，继续找另一位；若家人本身造成威胁，可找校内等家庭外可信任成人。'},
 {g:5,m:2,name:'表达了却没用怎么办',kind:'方法的边界',view:()=>task('好好表达后，对方仍不配合呢？','方法可以帮助表达，但不是万能的。',[['可以换方式','换合适时间，或请老师协助沟通。'],['涉及伤害','先到安全处，立即找能提供帮助的大人。'],['别责怪自己','关系没改善，不等于你表达得不够好。']], '有情绪，不等于生病；需要帮助，也不必等到特别严重。'),notes:'30秒独立想、同桌各20秒、50秒回应与总结。若说“那就一直忍”，问“谁可以一起帮忙？”若说“是我没说好”，说明对方行为与环境也影响结果。正常情绪不等于诊断；持续影响生活可找成人或专业人员，眼前风险立即寻求帮助。'},
 {g:6,m:2,name:'三行方法卡',kind:'留下成果',view:methodCard,notes:'学生在纸上写三行，也可继续填写小宁的虚构故事；不收姓名或私人困扰，不要求交卡。教师在网页输入时仅使用虚构示例。1分钟填写，1分钟自己检查具体、可行、安全。'},
 {g:6,m:1,name:'自愿分享方法',kind:'分享与检查',view:()=>task('愿意的话，分享你选的一步。','邀请2位，各说20秒；教师用20秒回应。',[['具体','别人能听懂要做什么吗？'],['可行','现在能开始，或知道找谁帮忙吗？'],['安全','能保护自己和别人吗？']], '只分享方法，不必说私人经历；可以选择不分享。'),notes:'最多2人，各20秒，教师20秒归纳。若没人分享，读一个虚构方法卡：“我有点着急；先圈出不会的一题；找任课老师”。不收集心理健康分数。'},
 {g:6,m:1,name:'结束与机动',kind:'总结',view:()=>task('带走一个愿意用的方法，就够了。','今天练过的，明天可以再试。',[['我有点……','说清感受'],['我可以先……','选择具体行动'],['我可以找……','需要时获得支持']], '没马上开心，也不代表做错了。可以调整方法、休息或寻求帮助。'),notes:'预留1分钟总结与机动。若前面超时，压缩公开分享，保留表达第二轮和方法卡，不用牺牲核心练习来补播视频。个人困扰课后单独衔接成人支持。'}
];
let workshopIndex=0,roundTimer=null,roundRunning=false,roundRemaining=60,roundDeadline=0;
function stopRound(){clearInterval(roundTimer);roundTimer=null;roundRunning=false}
function drawRound(){const c=$('#roundClock');if(c)c.textContent=timeText(roundRemaining);const b=$('#roundPause');if(b)b.textContent=roundRunning?'暂停':'继续'}
function startRound(seconds){stopRound();roundRemaining=seconds;roundDeadline=performance.now()+seconds*1000;roundRunning=true;drawRound();roundTimer=setInterval(()=>{roundRemaining=Math.max(0,Math.ceil((roundDeadline-performance.now())/1000));if(!roundRemaining)stopRound();drawRound()},100)}
function workshopMove(index){if(index<0||index>=workshopSlides.length)return;stopTimer();stopCartoon();stopRound();document.querySelectorAll('audio,video').forEach(m=>m.pause());workshopIndex=index;step=workshopSlides[index].original??0;phase=1;remaining=total=60;lastPrompt='';cartoonElapsed=0;roundRemaining=60;render();window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true})}
render=function(){const s=workshopSlides[workshopIndex],g=workshopGroups[s.g];step=s.original??0;phase=1;$('#main').innerHTML=`<div class="screen-content workshop-screen"><div class="section-bar"><strong><span class="work-section-number">${String(s.g+1).padStart(2,'0')}</span> ${g[0]}</strong><span class="page-kind">${s.kind}</span></div>${s.view()}</div>`;$('#progress').innerHTML=workshopGroups.map((a,i)=>`<button data-go="${i}" class="${i===s.g?'current':i<s.g?'done':''}" aria-label="第${i+1}部分：${a[0]}" ${i===s.g?'aria-current="step"':''}></button>`).join('');$('#stepLabel').textContent=`${workshopIndex+1} / ${workshopSlides.length} · ${s.name}`;$('#prev').disabled=workshopIndex===0;$('#next').disabled=workshopIndex===workshopSlides.length-1;$('#next').textContent=workshopIndex===workshopSlides.length-1?'本课结束':'下一页 →';document.body.classList.toggle('method-print',s.view===methodCard);requestAnimationFrame(fitScreen)};
nextPart=function(){workshopMove(workshopIndex+1)};previousPart=function(){workshopMove(workshopIndex-1)};go=function(group){const i=workshopSlides.findIndex(s=>s.g===group);if(i>=0)workshopMove(i)};
openMap=function(){$('#mapItems').innerHTML=workshopGroups.map((g,i)=>`<section class="map-section"><h3><button data-go="${i}">${String(i+1).padStart(2,'0')} ${g[0]}</button></h3><p>${g[1]}—${g[2]}分钟 · ${g[2]-g[1]}分钟</p>${workshopSlides.map((s,j)=>s.g===i?`<button data-work-page="${j}">${s.name}<small>${s.m}分钟</small></button>`:'').join('')}</section>`).join('');$('#mapDialog').showModal()};
openTeacher=function(){const s=workshopSlides[workshopIndex],g=workshopGroups[s.g];const t=workshopSlides.slice(0,workshopIndex).reduce((a,b)=>a+b.m,0);$('#teacherContent').innerHTML=`<h2>${s.name}</h2><p class="big-dialog-note">${t}—${t+s.m}分钟 · 本页${s.m}分钟<br>本环节：${g[1]}—${g[2]}分钟</p><div class="note-block"><h3>直接带领</h3><p>${s.notes}</p></div><div class="note-block"><h3>参与入口</h3><p>${participation} 不让少数人的分享代替全体练习。冷场时教师用虚构示例继续。</p></div><details><summary>理论备课与追问参考（不逐页讲给学生）</summary>${theoryDetails.flat().map(a=>`<div class="note-block"><h3>${a.title}</h3><p>${a.notes}</p></div>`).join('')}</details><details><summary>备用短片与资料</summary><p>备用45秒短片仅替换示范，不能挤占第二轮表达练习。课堂不使用实时AI问答。</p><button id="openOriginalVideo">播放备用短片 · 45秒</button>${referenceList()}</details>`;$('#teacherDialog').showModal()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.workPage!==undefined){$('#mapDialog').close();workshopMove(+b.dataset.workPage)}if(b.dataset.round){startRound(+b.dataset.round);document.querySelectorAll('[data-round]').forEach(x=>x.classList.toggle('primary',x===b))}if(b.id==='roundPause'){if(roundRunning){stopRound();drawRound()}else if(roundRemaining>0)startRound(roundRemaining)}if(b.id==='printMethod')window.print();if(b.id==='clearMethod'){methodAnswers.fill('');render()}});
document.addEventListener('input',e=>{if(e.target.dataset.methodAnswer!==undefined)methodAnswers[+e.target.dataset.methodAnswer]=e.target.value});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRound();drawRound()}});
workshopMove(0);
